theme: jekyll-theme-minimal
title: Mastery Tracker
description: I am working towards studying 10,000 hours of computer science and engineering topics before I turn 30. This GitHub Pages deployment will serve as a blog/analytics reference to keep me motivated and on-track.